apiVersion: 1

datasources:
  - name: prometheus-main
    type: prometheus
    uid: prometheus-main
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST

  - name: prometheus-secondary
    type: prometheus
    uid: prometheus-secondary
    url: http://prometheus:9090
    access: proxy
    jsonData:
      httpMethod: POST

  - name: thanos-querier
    type: prometheus
    uid: thanos-querier
    url: http://thanos-querier:9090
    access: proxy
    jsonData:
      httpMethod: POST
