global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: demo
    replica: "0"

scrape_configs:
  - job_name: "exporter"
    honor_labels: true
    static_configs:
      - targets: ["exporter:9099"]
